### ISSUE TITLE
have confirm works like `git add -p`

### ISSUE THREAD

**Issue by teto** [papis/papis#169] opened 2019-04-10 06:19 UTC
When I run an update on my document, I have to say yes to every update in interactive mode.
I would like to just be interactive for the first few questions and depending on if everything looks ok,  skip the remaining confirmation via yes or no. 
so basically, instead of accepting Y/n, papis would accept several answers like `git add -p`: 
`Stage this hunk [y,n,q,a,d,j,J,g,/,e,?]? `
a => would accept every remaining update
d => ignore remaining updates.
I can provide a PR.

**Comment by alejandrogallo** [comment] 2019-04-10 23:05
This would be indeed cool, but some work is needed... PR would be great

**Comment by teto** [comment] 2019-04-11 04:29
will try to come up with sthg this week end.

**Comment by alejandrogallo** [comment] 2019-09-13 17:22
Kind of duplicate of #189

**Closed by alejandrogallo** 2019-09-13 17:22 UTC
