### ISSUE TITLE
Unable to update from ISBN

### ISSUE THREAD

**Issue by capaldo** [papis/papis#89] opened 2018-08-07 22:08 UTC
running the following:
`papis -l subject_reference update --from-isbnplus ISBN -i`
results in:
`ERROR:Command:urllib failed to download`

any fix for this?

**Comment by alejandrogallo** [comment] 2018-08-07 22:09
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @alejandrogallo.

Possibly related issues are https://github.com/alejandrogallo/papis/issues/23 (add --from-isbn), https://github.com/papis/papis/issues/77 (update --all?), https://github.com/papis/papis/issues/62 (unable to open notes.tex), https://github.com/papis/papis/issues/80 (papis update --force overwrites unique ref tag), and https://github.com/papis/papis/issues/31 (Update database model to allow for whoosh backend).

**Comment by alejandrogallo** [comment] 2018-08-07 22:38
Hi, thanks for reporting, right now I'm busy preparing version v0.7, could you write a concrete example
with a real isbn ? The isbnplus sometimes has some trouble finding documents.
Cheers!

**Comment by alejandrogallo** [comment] 2018-08-07 22:58
I double checked my credentials at https://isbnplus.3scale.net/
where I registered the app papis, and not even the examples are working, so it is on their side
the problem, it is confirmed to be broken. I'll have to send them an email asking for an explanation.
Until then... this remains open

**Comment by alejandrogallo** [comment] 2018-09-17 22:30
This should actually be fixed now, since new and better support has been added for isbn.

**Closed by alejandrogallo** 2018-09-17 22:30 UTC
Labels: 3rdparty-limitation, enhancement
